version: '3.8'
services:
  pipoca-ia-app:
    build: .
    container_name: pipoca-ia-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - database

  database:
    image: postgres:16
    container_name: db_postgre
    ports:
      - "5232:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: { }

