CREATE TABLE tb_filmes
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome      VARCHAR(255)                            NOT NULL,
    categoria VARCHAR(255)                            NOT NULL,
    nota      DOUBLE PRECISION                        NOT NULL,
    CONSTRAINT pk_tb_filmes PRIMARY KEY (id)
);